### ISSUE TITLE
Create an improved variety selector on the order edit page

### ISSUE THREAD

**Issue by tonygilkerson** [ohiobarn/flowerpower#2]
Currently we have a basic html select list

**Comment by tonygilkerson** [comment]
per our meeting here are the items we discussed:

* Remove the tags that show under the search bar.  We are going to have individual filter select stuff
* Use a flower icon for the color filter in place of the little circle.  Same goes for the color circle on the card
* Add category filter.  For now you can just have a Flower, Filler, Foliage radio button but I will talk to your mom to see if we can get an icon for each
* Add an "Add Item" button at the end of the order detail list
* When you click the "Add Item" button the search fields are shown and the full list of varieties shows by default
* Each variety shown in the search list will have the following things that are clickable, i.e. when clicked will add to your search filter: 
  1. color flower icon
  2. Category button
  3. Price $$
  4. Crop
  5. Bunches (need to find a a way to make this easy, maybe do like your Kroger app with big green/red buttons)
* Order Save and Cancel buttons need to move somewhere else, maybe the top of the order
* Need a "clear search" and a "done search" (not sure how this should look)
* For each filter icon (flower, category and $$$) find a clean way to indicate that the icon is selected.  Maybe a circle appears around the icon, or maybe the background turn a black or maybe the an bar/underline shows under the icon.  But the "is selected" visual should probably be the same for all.

**Comment by tonygilkerson** [comment]
per our meeting again...

* Remove the Don and Reset buttons on the Line Item (LI) search
* Search results show up as you type in the search filed (must type at least three characters before it starts to filter)
* Clicking anywhere on the LI should select that item, end the search, and show you the new LI card
* Remove Bunches drop down on LI
* Add ability to edit Bunches [ + / - buttons maybe] on the LI card
* Need order total at the bottom

Things that we discussed but are not as important as the above:
* Add Color, Category and Tier icons to the LI
* Clicking the icon adds to the filter (You can mock this up for now, but it does not have to work yet)

**Comment by tonygilkerson** [comment]
Things it validate:

* Is one text search good or do we need tags?
* Is the Tire really going to be used?  If so is $, $$ and $$$ good for all six tiers?
* What are the search paterns?  We optimized for simplicity and so we do not have a multi select search list,  is this good?
*

**Comment by claygilk** [comment]
Things to work on next:

- Remove the Done button (replace with x in top right corner?)
- Order Save and Cancel buttons need to move somewhere else, maybe the top of the order
- setting qty to 0 removes item from order
- add a button to remove an item from the order
- Each variety shown in the search list will have the following things that are clickable, i.e. when clicked will add to your search filter:

1. color flower icon
2. Category button
3. Price $$
4. Crop
5. Bunches (need to find a a way to make this easy, maybe do like your Kroger app with big green/red buttons)

**Comment by tonygilkerson** [comment]
done, mostly
